# Generated by Django 3.2.7 on 2021-09-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в Телеграме')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='Имя пользователя в Телеграме')),
                ('first_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Фамилия')),
                ('contact', models.CharField(blank=True, default='', max_length=256, verbose_name='Контакт для связи')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Профиль',
            },
        ),
    ]
