# Generated by Django 3.2.7 on 2021-10-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_excahnge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excahnge',
            new_name='Exchange',
        ),
    ]
