# Generated by Django 3.2.7 on 2021-10-02 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_rename_excahnge_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
